AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation template: This template builds an EC2 instance attached to
  an elastic IP address, and given an IAM policy allowing it full access to S3.
Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: The off-campus IP address range to SSH to the EC2 instances. UVA Campus is automatically granted.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 1.2.3.4/32
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyName
      ImageId: ami-0c7217cdde317cfec
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: ds2022-ec2-with-s3
      UserData:
        Fn::Base64: 
          !Sub |
          #!/bin/bash -xe
          apt update && apt install python3-pip -y
          python3 -m pip install boto3 awscli

  AddVolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      Size: 20
      VolumeType: gp2
      Encrypted: true
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
    DeletionPolicy: Delete

  AttachEBS:
    Type: 'AWS::EC2::VolumeAttachment'
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref AddVolume
      Device: /dev/sdf
    DeletionPolicy: Delete

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '128.143.0.0/16'
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '199.111.0.0/16'
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'
          
  IPAddress:
    Type: 'AWS::EC2::EIP'

  IPAssoc:
    Type: 'AWS::EC2::EIPAssociation'
    Properties:
      InstanceId: !Ref EC2Instance
      EIP: !Ref IPAddress

  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: ec2-instance-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
    DeletionPolicy: Delete

  InstanceS3Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: S3Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource:
              - !Sub arn:aws:s3:::*
              - !Sub arn:aws:s3:::/*
      Roles:
        - !Ref InstanceRole
    DeletionPolicy: Delete

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: ec2-instance-profile
      Path: /
      Roles:
        - !Ref InstanceRole
    DeletionPolicy: Delete

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  InstanceIPAddress:
    Description: IP address of the newly created EC2 instance
    Value: !Ref IPAddress